watch_stylesheet: true
watch_config: true
debug: false
update_check: true
komorebi:
  start_command: komorebic start --whkd
  stop_command: komorebic stop --whkd
  reload_command: komorebic stop --whkd && komorebic start --whkd
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      align: center
    blur_effect:
      enabled: false
      dark_mode: true
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
      hide_on_fullscreen: false
    dimensions:
      width: "100%"
      height: 40
    padding:
      top: 0
      left: 3
      bottom: 0
      right: 10
    widgets:
      left: 
        [
          "glazewm_workspaces",
          "mediaico",
          "media",
          "language",
        ]
      center:
        [ 
          "clock",
        ]
      right:
        [
          "systray",
          "volume",
          "wifi",
          "brightness",
          "battery",
          "power_menu",
        ]
    layouts:
      center:
        alignment: center
        stretch: false
widgets:
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "<span>\ue8ac</span>"
      uptime: true
      show_user: true
      blur: true
      blur_background: true
      animation_duration: 120
      button_row: 3
      profile_image_size: 80
      buttons:
        lock: ["\ue88d", ""]
        sleep: ["\ue213", ""]
        restart: ["\uf053", ""]
        shutdown: ["\uf8c7", ""]
        signout: ["\ue879", ""]
        cancel: ["\ue14c", ""]
      keybindings:
          - keys: "alt+shift+k"
            action: "toggle_power_menu"
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\ue7f4</span> {count}"
      label_alt: "<span>\ue7f4</span>"
      hide_empty: false
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "do_nothing"
        on_middle: "toggle_label"
  brightness:
    type: "yasb.brightness.BrightnessWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "<span>{icon}</span> {percent}%"
      tooltip: true
      hide_unsupported: true
      brightness_toggle_level: [0, 50, 100]
      auto_light: false
      auto_light_icon: "\udb80\udce1"
      auto_light_night_level: 35
      auto_light_night_start_time: "19:00"
      auto_light_night_end_time: "06:45"
      auto_light_day_level: 75
      brightness_icons: [
        "\ue3a9",  # Icon for 0-25% brightness
        "\ue3aa",  # Icon for 26-50% brightness
        "\ue3aa",  # Icon for 51-75% brightness
        "\ue3ac"   # Icon for 76-100% brightness
      ]
      brightness_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 8
        offset_left: -6
        brightness_icon: "\ue3aa"
        contrast_icon: "\ueb37"
      callbacks:
        on_left: "toggle_brightness_menu"
        on_right: "toggle_label"
  mediaico:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\udbbf\udfd8"
      label_alt: "\udbbf\udfd8"
      class_name: "media_icon"
    callbacks:
      on_left: "do_nothing"
      on_middle: "do_nothing"
      on_right: "do_nothing"
  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: ":("
      hide_empty_workspaces: true
      hide_if_offline: false
      container_padding: 
        top: 0
        left: 8
        bottom: 0
        right: 8
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: ""
      label_alt: ""
      label_no_window: "\ue87d"
      label_icon: true
      label_icon_size: 16
      max_length: 20
      max_length_ellipsis: "..."
      monitor_exclusive: true
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%d %B   %I:%M}"
      label_alt: "{%A, %d %B %Y   %H:%M}"
      timezones: []
      update_interval: 1000
      calendar:
        alignment: "center"
        blur: true
        offset_top: 9
        round_corners: true
        round_corners_type: "normal"
        border_color: "none"
        direction: "down"
        show_holidays: true
        show_week_numbers: false
        holiday_color: "#ff9f00"
      callbacks:
        on_left: "toggle_calendar"
        on_middle: "do_nothing"
        on_right: "do_nothing"
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title}"
      label_alt: "{artist}"
      hide_empty: true
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "open_media_source"
        on_right: "toggle_label"
      max_field_size:
        label: 30
        label_alt: 36
      show_thumbnail: false
      controls_hide: true
      icons:
        prev_track: "\ue045"
        next_track: "\ue044"
        play: "\ue1c4"
        pause: "\ue1a2"
      media_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "left"
        direction: "down"
        offset_top: 8
        offset_left: -22
        thumbnail_corner_radius: 6
        thumbnail_size: 90
        max_title_size: 60
        max_artist_size: 20
        show_source: true
      media_menu_icons:
        play: "\ue1c4"
        pause: "\ue1a2"
        prev_track: "\ue045"
        next_track: "\ue044"
      scrolling_label:
        enabled: false
        update_interval_ms: 33
        style: "left"
        separator: " | "
        label_padding: 0
        always_scroll: false
        ease_slope: 20
        ease_pos: 0.8
        ease_min: 0.5
  systray:
    type: yasb.systray.SystrayWidget
    options:
      label_collapsed: "\ue313"
      label_expanded: "\ue316"
      label_position: "right"
      icon_size: 16
      pin_click_modifier: "alt"
      show_unpinned: false
      show_unpinned_button: true
      show_in_popup: true
      popup:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: None
        alignment: "center"
        direction: "down"
        offset_top: 10
        offset_left: 0
      show_battery: false
      show_volume: false
      show_network: false
      tooltip: true
  language:
    type: yasb.language.LanguageWidget
    options:
      label: "<span>\uf028</span> {lang[country_code]}"
      label_alt: "{lang[full_name]}"
      update_interval: 5
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      language_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "None"
        alignment: "left"
        direction: "down"
        offset_top: 10
        offset_left: 0
        show_layout_icon: true
        layout_icon: "\uf028"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span style=\"text-align:center;\">{icon}</span>"
      icons:
        - "\ue04f" # Icon for muted
        - "\ue04e" # Icon for 0-10% volume
        - "\ue04d" # Icon for 11-30% volume
        - "\ue04d" # Icon for 31-60% volume
        - "\ue050" # Icon for 61-100% volume
      audio_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "none"
        alignment: "center"
        direction: "down"
        offset_top: 8
        offset_left: -148
        show_apps: true
        show_app_labels: false
        show_apps_expanded: true
        app_icons:
          toggle_down: "\ue313"
          toggle_up: "\ue316"
      callbacks:
        on_right: "toggle_mute"
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span style=\"text-align:center;\">{wifi_icon}</span>"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      ethernet_label: "<span>{wifi_icon}</span>"
      ethernet_label_alt: "<span>{wifi_icon}</span>{ip_addr}"
      ethernet_icon: "\ue8be"
      get_exact_wifi_strength: false # Optional. Will require location access permission if true.
      wifi_icons: [
          "\uf0b0", # Icon for 0% strength
          "\uebd6", # Icon for 1-24% strength
          "\uebe1", # Icon for 25-49% strength
          "\ue1ba", # Icon for 50-74% strength
          "\ue1d8", # Icon for 75-100% strength
        ]
      menu_config:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "none"
        alignment: "right"
        direction: "down"
        offset_top: 9
        offset_left: 0
        wifi_icons_secured: ["\uf58f", "\uf58e", "\uf58d", "\uf532"]
        wifi_icons_unsecured: ["\uf0ef", "\uf0ef", "\uf0ef", "\uf0ef"]
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label_alt: "<div style=\"text-align:center;\">{percent}</div><span>{icon}</span>"
      label: "<div style=\"text-align:center;\"></div>"
      update_interval: 5000
      time_remaining_natural: true
      hide_unsupported: True
      charging_options:
        icon_format: "{charging_icon}"
        blink_charging_icon: false
        blink_interval: 500
      status_thresholds:
        critical: 10
        low: 25
        medium: 75
        high: 97
        full: 100
      status_icons:
        icon_charging: "\uea0b"
        icon_critical: "\ueb58"
        icon_low: "\ueb58"
        icon_medium: "\ueb58"
        icon_high: "\ueb58"
        icon_full: "\ueb58"
      progress_bar: 
        enabled: true
        progress_type: "linear_horizontal"
        size: 22
        thickness: 13
        radius: 4
        color: "#E7FFE5"
        background_color: "#637266"
  custom_battery:
    type: "yasb.custom.CustomWidget"
    options:
      label: ""
      class_name: "custom-battery-widget"
      exec_options:
        run_cmd: "powershell ~\\.config\\yasb\\batterywidget.ps1"
        run_interval: 300000 # run every 5 min
        return_format: "string"
        hide_empty: false
      callbacks:
        on_left: "do_nothing"
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>{icon}</span><div style=\"text-align:center;\">{count}</div>"
      label_alt: "{count} notifications"
      hide_empty: false
      tooltip: true
      icons: {"new": "\uf189", "default": "\ue0ca"}
      callbacks:
        on_left: "toggle_notification"
        on_right: "do_nothing"
